### ISSUE TITLE
How to generate the train dataset?

### ISSUE THREAD

**Issue by LearnerInGithub** [argman/EAST#2] opened 2017-08-01 09:52 UTC
@zxytim @argman Hello, thanks for your sharing!  Now I am curious about the format of the train dataset, so could provide a brief descriptions about it?  Thanks very much!

**Comment by argman** [comment] 2017-08-01 10:14
see in training samples

**Comment by LearnerInGithub** [comment] 2017-08-01 14:22
@argman @zxytim  Why the code always stuck at time.sleep(0.01) in the def get_batch(num_workers=10, **kwargs):  after read through the the images?

**Comment by argman** [comment] 2017-08-02 01:29
if you dont have enough cpu-cores, you should reduce the num_readers to a suitable number.

**Comment by LearnerInGithub** [comment] 2017-08-02 03:25
@argman Even I change the readers number to 4(I am sure I have at least 28 free cores), the stuck problem still there, below is the part of running log:
image_list.shape:(1000,)
1000 training images in ICDAR2015
enqueuer.queue isnot empty, sleep 0.01
enqueuer.queue isnot empty, sleep 0.01
enqueuer.queue isnot empty, sleep 0.01

**Comment by argman** [comment] 2017-08-02 08:13
I dont encounter your problem, maybe it's the version of keras, I use keras to provide mulithread
what's your keras version ?

**Comment by LearnerInGithub** [comment] 2017-08-03 07:35
@argman My keras version is 2.0.0,  and which version of keras you used?

**Comment by argman** [comment] 2017-08-03 08:17
I've updated the code, no need to install keras now.

**Comment by LearnerInGithub** [comment] 2017-08-03 12:00
@argman Now I faced new problem while training, the tips is warning, the warning info:
icdar.py:210: RuntimeWarning: divide by zero encountered in float_scalars
  theta = np.arctan((poly[3][0] - poly[0][0]) / (poly[3][1] - poly[0][1]))
icdar.py:216: RuntimeWarning: divide by zero encountered in float_scalars
  theta = np.arctan((poly[2][0] - poly[1][0]) / (poly[2][1] - poly[1][1]))

**Comment by argman** [comment] 2017-08-03 13:05
its caused by some small polygons, you can ignore it.

**Comment by zxytim** [comment] 2017-08-07 17:05
@LearnerInGithub The newest version is using np.arctan2, the problem should be fixed.

**Closed by zxytim** 2017-08-07 17:05 UTC

**Comment by rmmal** [comment] 2017-09-07 13:36
@LearnerInGithub  how did you solved the problem of being stucked in sleep(0.01) ??

**Comment by yangxuehang** [comment] 2017-10-06 14:33
@LearnerInGithub @rmmal  how did you solve the problem of being stucked in sleep(0.01) ??
